# Generated by Django 5.0.3 on 2024-03-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="текст 2-ого блока 'О компании'")),
            ],
            options={
                'verbose_name': 'о компании',
            },
        ),
    ]
