# Generated by Django 5.0.3 on 2024-03-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'о компании', 'verbose_name_plural': 'о компании'},
        ),
    ]
