# Generated by Django 5.0.3 on 2024-03-11 09:13

import ckeditor_uploader.fields
import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_about_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_image', models.ImageField(upload_to=company.models.upload_to, verbose_name='изображение, превью')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='содержание проекта')),
                ('preview', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
