# Generated by Django 5.0.3 on 2024-04-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('metaltraders', models.TextField(verbose_name='металлотрейдерам')),
                ('enterprises', models.TextField(verbose_name='предприямтиям')),
            ],
            options={
                'verbose_name': 'сотрудничество',
                'verbose_name_plural': 'сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='SpecialOfferDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': "описание раздела 'спецпредложение'",
                'verbose_name_plural': "описание раздела 'спецпредложение'",
            },
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='заголовок спецпердложения')),
                ('text', models.TextField(verbose_name='спецпредложение')),
            ],
            options={
                'verbose_name': 'спецпредложение',
                'verbose_name_plural': 'спецпредложения',
            },
        )
    ]
