# Generated by Django 5.0.3 on 2024-04-22 19:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_cooperation_specialofferdescription_specialoffers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialofferdescription',
            options={'verbose_name': "описание раздела 'Спецпредложения'", 'verbose_name_plural': "описание раздела 'Спецпредложения'"},
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='description',
            field=models.TextField(verbose_name='"Сотрудничество", первый экран'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='enterprises',
            field=ckeditor.fields.RichTextField(verbose_name='предприямтиям'),
        ),
        migrations.AlterField(
            model_name='cooperation',
            name='metaltraders',
            field=ckeditor.fields.RichTextField(verbose_name='металлотрейдерам'),
        ),
    ]
