# Generated by Django 5.0.3 on 2024-04-25 06:55

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_specialofferdescription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='заголовок изображения')),
                ('img', models.ImageField(upload_to=company.models.upload_to, verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'изображение первого слайдера',
                'verbose_name_plural': 'изображения первого слайдера',
            },
        ),
        migrations.CreateModel(
            name='Slider2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='заголовок изображения')),
                ('img', models.ImageField(upload_to=company.models.upload_to, verbose_name='изображение превого слайдера')),
            ],
            options={
                'verbose_name': 'изображение второго слайдера',
                'verbose_name_plural': 'изображения второго слайдера',
            },
        ),
    ]
