# Generated by Django 5.0.3 on 2024-03-05 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlloyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'марка сплава',
                'verbose_name_plural': 'марки сплава',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'материал продукции',
                'verbose_name_plural': 'материалы продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'стандарт продукции',
                'verbose_name_plural': 'стандарты продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'состояние поставки',
                'verbose_name_plural': 'состояния поставки',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'тип продукции',
                'verbose_name_plural': 'типы продукции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_min', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='нижняя граница толщины, мм')),
                ('thickness_max', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='верхняя граница толщины, мм')),
                ('width_min', models.IntegerField(verbose_name='нижняя граница ширины, мм')),
                ('width_max', models.IntegerField(verbose_name='верхняя граница ширины, мм')),
                ('length_min', models.IntegerField(verbose_name='нижняя граница длины, мм')),
                ('length_max', models.IntegerField(verbose_name='верхняя граница длины, мм')),
                ('alloy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.alloytype', verbose_name='марка сплава')),
                ('materiral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productmaterial', verbose_name='материал продукции')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productstandard', verbose_name='стандарт продукции')),
                ('supply_condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productsupplycondition', verbose_name='состояние поставки')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.producttype', verbose_name='тип продукции')),
            ],
            options={
                'verbose_name': 'продукция',
                'verbose_name_plural': 'продукция',
            },
        ),
    ]
