# Generated by Django 5.0.3 on 2024-03-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_producttype_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_category',
        ),
    ]
