# Generated by Django 5.0.3 on 2024-03-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_type_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaterial',
            name='slug',
            field=models.SlugField(default='alyuminiy', unique=True, verbose_name='url'),
            preserve_default=False,
        ),
    ]
