# Generated by Django 5.0.3 on 2024-03-15 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_materiral_product_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thickness_min',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_min',
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='верхняя граница длины, мм'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='верхняя граница толщины, мм'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, max_length=30, null=True, verbose_name='верхняя граница ширины, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productstandard', verbose_name='стандарт продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product.productsupplycondition', verbose_name='состояние поставки'),
        ),
        migrations.AlterField(
            model_name='productstandard',
            name='standard',
            field=models.CharField(max_length=128, unique=True, verbose_name='название'),
        ),
    ]
