# Generated by Django 5.0.3 on 2024-03-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_length_max_remove_product_length_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='верхняя граница длины, мм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='верхняя граница ширины, мм'),
        ),
    ]
