# Generated by Django 5.0.3 on 2024-03-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='контактное лицо')),
                ('number', models.CharField(max_length=20, verbose_name='номер телефона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'запрос звонка',
                'verbose_name_plural': 'запросы звонков',
            },
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('call_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientRequests.call')),
                ('product_details', models.CharField(max_length=50, verbose_name='название')),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='вид деятельности')),
                ('company_name', models.CharField(max_length=100, verbose_name='наименование предприятия или И.П.')),
            ],
            options={
                'verbose_name': 'запрос коммерческого предложения',
                'verbose_name_plural': 'запросы коммерческого предложения',
            },
            bases=('clientRequests.call',),
        ),
    ]
