# Generated by Django 5.0.3 on 2024-03-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_preview',
            field=models.CharField(default=models.TextField(verbose_name='текст статьи'), max_length=100, verbose_name='пердпросматриваемый контент'),
        ),
    ]
