# Generated by Django 5.0.3 on 2024-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=models.CharField(max_length=100, verbose_name='пердпросматриваемый контент'),
        ),
    ]
