# Generated by Django 5.0.3 on 2024-03-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_text_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='text_preview',
            new_name='content_preview',
        ),
    ]
