# Generated by Django 5.0.3 on 2024-03-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_text_article_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_preview',
        ),
    ]
