# Generated by Django 5.0.3 on 2024-03-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='регион')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('address', models.CharField(max_length=50, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес электронной почты')),
            ],
            options={
                'verbose_name': 'адрес электронной почты',
                'verbose_name_plural': 'адреса электронной почты',
            },
        ),
        migrations.CreateModel(
            name='TelphoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='номер телефона')),
            ],
            options={
                'verbose_name': 'номер телефона',
                'verbose_name_plural': 'номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='название отдела')),
                ('telephone_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='contacts.telphonenumber', verbose_name='телефон отдела')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отдел',
            },
        ),
    ]
