# Generated by Django 5.0.3 on 2024-03-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telphonenumber',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='номер телефона'),
        ),
    ]
