# Generated by Django 5.0.3 on 2024-03-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_department_options_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Код яндекс карты'),
        ),
    ]
